#include "Functions/Function.hpp"
#include "Functions/Pol.hpp"
#include "Functions/Constant.hpp"
#include "Functions/Sin.hpp"
#include "Functions/Cos.hpp"
#include "Functions/Max.hpp"
#include "Functions/Min.hpp"